name: Serializationapi
version: ${project.version}
main: fr.lucasprogram.serializationapi.Serializationapi
authors: [LucasProgram]
description: Used to serialize data and save to JSON file using GSON
website: http://lucasprogram.com/